[GLOBAL]
pantsd = false
pants_version = "2.24.0.rc0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.experimental.adhoc",
    "pants.backend.shell",
]

[python]
interpreter_constraints = [">=3.7"]


[source]
root_patterns = ["/src"]

[environments-preview.names]
workspace = "//:workspace"